// Code generated by fabricator-generate-go
//
// Modifications in code regions will be lost during regeneration!
package fabricatorgenerateplugingo

// region CODE_REGION(GEN)
//go:generate fabricator generate go
//go:generate fabricator generate project go
// endregion
